In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
[1,2,3,4,5,6]

[1, 2, 3, 4, 5, 6]

In [10]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  4,  5,  6])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
n[1]

array([4, 5, 6])

In [26]:
n[:, 1]

array([2, 5, 8])

In [29]:
n[1,:]

array([4, 5, 6])

In [30]:
n[2,:]

array([7, 8, 9])

In [31]:
n[2:,] = [1,1,1]

In [32]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [39]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
#add 1 to all element of this array
a + 1

array([1, 2, 3, 4, 5])